spring:
  application:
    name: warehouse-api
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:warehouse
    username: default_user
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: off
  h2:
    console:
      enabled: true
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
