spring:
  config:
    activate:
      on-profile: dev
    import: database-secrets.yml
  datasource:
    url: jdbc:mysql://${jpa-connection.host}:${jpa-connection.port}/${jpa-connection.database}
    username: ${jpa-connection.username}
    password: ${jpa-connection.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: off
